# build and test the application code with Maven, run checkstyle, generate sonar-scanner report and upload to SonarCloud, then check the Quality Gate status
name: vprofile actions
on: 
  workflow_dispatch:
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: vprofileapp
  EKS_CLUSTER: vprofile-eks

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # setup java 11 to be default for sonar-scanner
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  

      - name: Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      # install sonar-scanner cli, generate report and upload to SonarCloud
      - name: Setup SonarScanner
        uses: warchant/sonar-scanner-action@v7
      # run sonar-scanner with the necessary parameters to connect to SonarCloud and specify the project details
      - name: SonarQube Scan
        run: |
           sonar-scanner \
           -Dsonar.host.url=${{ secrets.SONAR_URL }} \
           -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
           -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
           -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
           -Dsonar.sources=src/ \
           -Dsonar.junit.reportsPath=target/surefire-reports/ \
           -Dsonar.jacoco.reportsPath=target/jacoco.exec \
           -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
           -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/  
      # Check the Quality Gate status and fail the workflow if it is not "passed"
      #- name: SonarQube Quality Gate check
        #id: sonarqube-quality-gate-check
        #uses: sonarsource/sonarqube-quality-gate-action@master
        #timeout-minutes: 5
        #env:
          #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          #SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
  # build the docker image, tag it with both "latest" and the GitHub run number, and push to Amazon ECR
  BUILD_AND_PUSH:
    needs: Testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to ECR
      run: |
        IMAGE_URI=${{ secrets.REGISTRY }}/${{ env.ECR_REPOSITORY }}
        
        docker build -t $IMAGE_URI:latest .
        docker tag $IMAGE_URI:latest $IMAGE_URI:${{ github.run_number }}
        
        docker push $IMAGE_URI:latest
        docker push $IMAGE_URI:${{ github.run_number }}
  DeployToEKS:
    needs: BUILD_AND_PUSH
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get kubeconfig
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}

      - name: Create or update ECR pull secret
        run: |
          kubectl delete secret regcred --ignore-not-found
          kubectl create secret docker-registry regcred \
            --docker-server=${{ secrets.REGISTRY }} \
            --docker-username=AWS \
            --docker-password=$(aws ecr get-login-password --region ${{ env.AWS_REGION }})

      - name: Deploy to EKS
        run: kubectl apply -f kubernetes/vpro-app/